media:
  input: src/media
  output: /media
content:
  - name: demos
    label: Demos
    type: collection
    path: 'src/pages/demos'
    filename: '{fields.series}/{fields.index}-{fields.title}.md'
    view:
      fields: [ title, published, series, index, date ]
      sort: [ index, title ]
      primary: title
    fields:
      - { name: published, label: Published, type: boolean, default: true }
      - { name: date, label: Date, type: date }
      - { name: series, label: Series, type: string }
      - { name: chapter, label: Chapter, type: number }
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text }
  - name: site
    label: Site settings
    path: 'src/data/site.json'
    type: file
    fields:
      - { name: title, label: Website title, type: string }
      - { name: description, label: Website description, type: string }
      - { name: url, label: Website URL, type: string }
      - { name: cover, label: Preview image, type: image, description: 'Image used in the social preview on social networks (e.g. Facebook, Twitter...)' }
